- name: configure postfix using debconf
  debconf:
    name: postfix
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: postfix/main_mailer_type, value: "Internet Site", vtype: select }
    - { question: postfix/mailname, value: "example.com", vtype: string }

- name: install postfix
  apt:
    name: postfix
    state: latest
  tags:
    - development
